//
//  Twine.swift
//  Twine
//
//  Created by Mitch on 2/12/25.
//

import Foundation

/// Container for localization string types & extensions
/// generated by [Twine](https://github.com/mitchtreece/Twine).
public struct Twine {}
